// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exqqpgsbpveeffpbxmdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4cXFwZ3NicHZlZWZmcGJ4bWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyOTc4MzAsImV4cCI6MjA1Njg3MzgzMH0.U47uFPhOhruPZWCA_jPdm-VbWgVeF-I7N4U-DF2kyjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);